title: 高羽的私人电子仓库
description: 个人电子书仓库，维护了一些历史、人文、计算机、哲学相关的书籍。
theme: minima
include:
  - _pages

# 下面是自定义配置的示例
# 多个自定义 CSS 的路径
sass:
  sass_dir: _sass
  style: :compressed

# 自定义的头信息、页脚等布局文件路径
layouts_dir: _layouts

# 插件 (确保你在 Gemfile 中已经添加了这些 gems)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# 自定义的颜色和字体示例
# main.scss 中可以覆盖这些样式
minima:
  color_scheme: dark # 更改色彩主题，可能是 'dark' 或其他 Minima 支持的色彩主题
  heading_font: "Helvetica Neue, Helvetica, Arial, sans-serif" # 更改标题字体
  body_font: "Georgia, serif" # 更改主体文本字体
