name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup the Ruby environment with the same version as your local development to ensure consistency
      - name: Setup Ruby for generating ebook list
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # or the version you use for Jekyll development
      
      # Install Ruby Gems, assuming Bundler is being used and there's a Gemfile
      - name: Install Ruby gems
        run: |
          bundle install

      # Custom step to generate your ebook list
      # Assuming you're using Rake, you need to ensure you have a Rakefile in your repo
      - name: Generate ebook list
        run: |
          bundle exec rake generate_ebook_list
      
      # After the list is generated, continue with your site building
      - name: Setup Pages
        uses: actions/configure-pages@v4
      
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
